#!/bin/sh
###############################################################
#                                                             #
#                                  __ _                       #
#              _ __ ___ _ __ ___  / _| |_   _                 #
#             | '__/ _ \ '_ ` _ \| |_| | | | |                #
#             | | |  __/ | | | | |  _| | |_| |                #
#             |_|  \___|_| |_| |_|_| |_|\__, |                #
#                                       |___/                 #
#                                                             #
#                                                             #
###############################################################
#                                                             #
#           https://github.com/remfly/dotfiles                #
#                                                             #
###############################################################

## Defaults ##
pgrep -x sxhkd > /dev/null || sxhkd &

## General settings ##
bspc config border_width        2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

## Colors ##
bspc config normal_border_color "#3B4252"
bspc config active_border_color "#4C566A"
bspc config focused_border_color "#4C566A"
bspc config presel_feedback_color "#4C566A"

## Rules ##
bspc rule -a alacritty locked=true
bspc rule -a Mictray state=floating centered=true
bspc rule -a Pavucontrol state=floating centered=true
bspc rule -a Blueman-manager state=floating centered=true
bspc rule -a Blueman-services state=floating centered=true
bspc rule -a Display state=floating centered=true
bspc rule -a Thunar state=floating centered=true
bspc rule -a Solaar state=floating centered=true
bspc rule -a Nm-connection-editor state=floating centered=true
bspc rule -a flameshot state=floating centered=true
bspc rule -a GParted state=floating centered=true
bspc rule -a Protonvpn state=floating centered=true
bspc rule -a Peek state=floating centered=true
bspc rule -a discord desktop='^7'

## Cleaning up ##
killall -eq solaar mictray blueman-applet picom dunst polkit-gnome-authentication-agent-1 parcellite unclutter volumeicon nm-applet > /dev/null
while pgrep -u $UID -x picom > /dev/null; do sleep 1; done

## Automatic Monitor Profile Setup ##
~/.config/bspwm/profile.sh &

## Set mouse cursor outside windows ##
xsetroot -cursor_name left_ptr &

## Set number lock on ##
numlockx on &

## Set keyboard repeat rate ##
xset r rate 240 44 &

## Auto-hide cursor ##
unclutter --timeout 10 --jitter 2 --exclude-root --ignore-scrolling -b

## Set wallpaper ##
nitrogen --restore &

## Authentication Agent ##
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Start compositor ##
picom --config ~/.config/picom/picom.conf -b

## Start System Applications ##
~/.config/scripts/autostart.sh
